version: '3.9'

volumes:
  pg_data:
    external: true

networks:
  postgres-net:
    external: true

secrets:
  postgres_password:
    external: true
  kong_config:
    external: true
  keycloak_config:
    external: true

services:
  db:
    image: postgres:17-alpine
    # profiles: [ "database" ]
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      #POSTGRES_PASSWORD: kong
    secrets:
      - postgres_password
      - source: kong_config
        target: /docker-entrypoint-initdb.d/kong_config.sql
      - source: keycloak_config
        target: /docker-entrypoint-initdb.d/keycloak_config.sql
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-d",
          "postgres",
          "-U",
          "postgres"
        ]
      interval: 30s
      timeout: 30s
      retries: 3
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 5
    #restart: on-failure
    stdin_open: true
    tty: true
    networks:
      - postgres-net
    ports:
      - 15432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data